#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend alimahmoud.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 418028-web-01 100.25.164.196:80
        server 418028-web-02 52.91.127.53:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
