#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
number=0
for ((number=0; number<10; number++)); do
    echo "Best School"
done
# another form of for:
# for number in {0..9}; do
#     echo "Best School"
# done
